# 显示设置
screen_width  : 1000
screen_height : 600
caption       : "One Man Fortress"


# 加载文件路径
image_background_path : './image/background.png'
image_player_path     : './image/stickman1.png'
image_zombie_path     : './image/zombie1.png'
image_bullet_path     : './image/laser_bullet.png'
score_path            : './data/score.txt'


# 角色设置
player_max_lives : 3
player_default_hp: 100
player_blink_duration: 3
player_speed: 10.

# 僵尸设置
zombie_number: 5
zombie_default_hp: 100
zombie_damage  : 30
zombie_kill_score: 100
zombie_kill_bonus_change: 0.5
zombie_speed: 1.
zombie_miss_chance: 0.1
zombie_miss_display_duration: 0.5   # 闪避信息显示时长


# 音效设置
sound_volume: 0.2
sound_path:
  dryfire   : "./sound/dryfire.wav"
  #'walk'      : './sound/walk.wav'


# 武器设置
weapon_height: 30

weapons:
  Pistol:
    ammo_limit: -1
    speed     : 20.
    damage    : 51.
    range     : 500.
    is_automatic  : False
    fire_interval : 0.5
    reload_duration: 1.
    sound_path    : "./sound/glock18-2.wav"
    image_path    : "./image/glock18.tga"


  Shotgun:
    ammo_limit: 10
    speed     : 20.
    damage    : 51.
    range     : 300.
    is_automatic  : False
    fire_interval : 0.5
    reload_duration: 2.
    sound_path    : "./sound/xm1014-1.wav"
    image_path    : "./image/xm1014.tga"

    spread    : 0.2


  Laser:
    ammo_limit: 50
    speed     : 10.
    damage    : 34.
    range     : 20.
    is_automatic  : True
    fire_interval : 0.01
    reload_duration: 3.
    sound_path    : "./sound/laser.mp3"
    image_path    : "./image/glock18.tga"

    generate_bullet_number: 100
    generate_bullet_interval: 10